name: Docker

on:
 workflow_dispatch:
 push:
    branches:
      - main # default branch
    paths:
      - Genshin-Impact-Wish-Simulator/src/**/**

jobs:
  DockerHub:
    name: Publish to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6.11.0
        with:
          context: .
          push: true
          tags: maizig/ysdm:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=maizig/ysdm:latest
          cache-to: type=inline
  Ghcr:
    name: Publish to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6.11.0
        with:
          context: .
          push: true
          tags: ghcr.io/animation-picker/genshin-impact:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/animation-picker/genshin-impact:latest
          cache-to: type=inline