name: Build app with Tauri

on:
    workflow_dispatch:
    workflow_call:

jobs:
    Build-Tauri:
        name: Build
        strategy:
          fail-fast: false
          matrix:
            os: [windows-latest,ubuntu-latest,macos-latest,macos-13]
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v4.1.1
          - name: install Rust stable
            uses: dtolnay/rust-toolchain@stable
          - name: install dependencies (ubuntu only)
            if: runner.os == 'Linux'
            run: |
              sudo apt-get update
              sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          - name: Use Node.js 20.x
            uses: actions/setup-node@v4.0.2
            with:
              node-version: "20"
          - name: Cache NPM dependencies
            uses: actions/cache@v4.0.2
            with:
              path: ./Genshin-Impact-Wish-Simulator/node_modules
              key: ${{ runner.OS }}-${{runner.arch}}-npm-frontend-cache
              restore-keys: |
                ${{ runner.OS }}-npm-frontend-cache
          - name: Cache Rust
            uses: Swatinem/rust-cache@v2.7.3
            with:
              prefix-key: "Cache-${{ runner.os }}-${{runner.arch}}"
              workspaces: "Genshin-Impact-Wish-Simulator/src-tauri"
              shared-key: "tauri"
          - name: Install Dependencies
            run: |
             cd Genshin-Impact-Wish-Simulator
             yarn install
          - name: Build
            run: |
             cd Genshin-Impact-Wish-Simulator
             yarn run tauri build
          - name: Upload (Windows)
            if: runner.os == 'windows'
            uses: actions/upload-artifact@v4.3.1
            with:
              name: genish-impact-Tauri-${{ runner.os }}
              path: Genshin-Impact-Wish-Simulator/src-tauri/target/release/bundle/
          - name: Upload Appimage (Linux)
            if: runner.os == 'Linux'
            uses: actions/upload-artifact@v4.3.1
            with:
              name: genish-impact-Tauri-${{ runner.os }}-appimage
              path: Genshin-Impact-Wish-Simulator/src-tauri/target/release/bundle/appimage/genish-impact_*.AppImage
          - name: Upload deb (Linux)
            if: runner.os == 'Linux'
            uses: actions/upload-artifact@v4.3.1
            with:
              name: genish-impact-Tauri-${{ runner.os }}-deb
              path: Genshin-Impact-Wish-Simulator/src-tauri/target/release/bundle/deb/genish-impact_*.deb
          - name: Upload dmg (Macos)
            if: runner.os == 'macos'
            uses: actions/upload-artifact@v4.3.1
            with:
              name: genish-impact-Tauri-${{ runner.os }}-dmg-${{runner.arch}}
              path: Genshin-Impact-Wish-Simulator/src-tauri/target/release/bundle/dmg/*.dmg